config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :markets, only: [:index, :show]
  get '/vendors/:id', to: 'vendors#show', as: 'vendor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = MarketFacade.all_markets
  end

  def show
    @market = MarketFacade.market(params[:id])
    @vendors = MarketFacade.vendors(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = VendorFacade.vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1>Markets</h1>
<% @markets.each do |market| %>
  <%= market[:attributes][:name] %> -
  <%= market[:attributes][:city] %> -
  <%= market[:attributes][:state] %> -
  <%= button_to 'More Info', market_path(market), method: :get %>
  </br>
<% end %>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1></br>
<p><%= @market.street %><p></br>
<p><%= @market.city %>, <%= @market.state %>, <%= @market.zip %><p></br>

<h2>Venors at our market:</h2>
<% @vendors.each do |vendor| %>
  <p><%= link_to "#{vendor.name}", "/vendors/#{vendor.id}" %></p>
<% end %>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>
<p>contact info:</p>
<p>name: <%= @vendor.contact_name %></p>
<p>phone: <%= @vendor.contact_phone %></p></br>
<p>credit accepted?: <%= @vendor.credit_accepted ? 'Yes' : 'No' %></p></br>
<p>description: <%= @vendor.description %></p>